import type {
  Category,
  DashboardMetric,
  DemoUser,
  FarmerProfile,
  MandiRate,
  Order,
  Product,
  Review,
  WeatherInsight,
} from "@/lib/types";
import { slugify } from "@/utils/format";

export const categories: Category[] = [
  {
    id: "fruits",
    name: "Fruits",
    slug: "fruits",
    description: "Seasonal fruits delivered from verified orchards.",
    accent: "from-orange-100 to-amber-50",
  },
  {
    id: "vegetables",
    name: "Vegetables",
    slug: "vegetables",
    description: "Daily farm-picked greens and staples.",
    accent: "from-emerald-100 to-lime-50",
  },
  {
    id: "grains",
    name: "Grains",
    slug: "grains",
    description: "Cleaned grains, pulses, and staples from producer groups.",
    accent: "from-yellow-100 to-stone-50",
  },
  {
    id: "dairy",
    name: "Dairy",
    slug: "dairy",
    description: "Fresh dairy and value-added rural produce.",
    accent: "from-sky-100 to-cyan-50",
  },
  {
    id: "organic",
    name: "Organic",
    slug: "organic",
    description: "Certified and naturally grown produce.",
    accent: "from-green-100 to-emerald-50",
  },
  {
    id: "seeds",
    name: "Seeds",
    slug: "seeds",
    description: "Farmer-selected seeds and starter kits.",
    accent: "from-rose-100 to-orange-50",
  },
];

export const farmers: FarmerProfile[] = [
  {
    id: "farmer-1",
    name: "Rakesh Kumar",
    farmName: "Kisan Fresh Farms",
    state: "Punjab",
    district: "Ludhiana",
    rating: 4.8,
    verified: true,
    yearsActive: 11,
    speciality: ["Organic vegetables", "Seasonal fruits"],
    responseTime: "within 20 mins",
  },
  {
    id: "farmer-2",
    name: "Anita Patil",
    farmName: "Sahyadri Growers",
    state: "Maharashtra",
    district: "Nashik",
    rating: 4.7,
    verified: true,
    yearsActive: 8,
    speciality: ["Onions", "Millets", "Export grapes"],
    responseTime: "within 35 mins",
  },
  {
    id: "farmer-3",
    name: "Mahesh Gowda",
    farmName: "Namma Naturals",
    state: "Karnataka",
    district: "Mysuru",
    rating: 4.9,
    verified: true,
    yearsActive: 13,
    speciality: ["Cold-pressed dairy", "Organic staples"],
    responseTime: "within 25 mins",
  },
];

function buildProduct(
  data: Omit<Product, "slug">,
): Product {
  return {
    ...data,
    slug: slugify(`${data.name}-${data.farmerName}`),
  };
}

export const products: Product[] = [
  buildProduct({
    id: "prod-1",
    name: "Premium Alphonso Mango Box",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "fruits",
    state: "Maharashtra",
    description:
      "Export-grade Alphonso mangoes harvested early morning, naturally ripened, and packed in shock-safe boxes.",
    tags: ["Seasonal", "Best seller", "Retail"],
    unit: "3 kg box",
    stock: 88,
    organic: true,
    price: 899,
    originalPrice: 1099,
    deliveryTime: "1-2 days",
    rating: 4.8,
    reviewCount: 138,
    images: [
      "from-amber-200 via-orange-100 to-white",
      "from-yellow-200 via-amber-100 to-white",
      "from-orange-200 via-rose-100 to-white",
    ],
    color: "from-amber-100 to-orange-50",
    harvestDate: "2026-04-20",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-2",
    name: "Residue-Free Baby Spinach",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "vegetables",
    state: "Punjab",
    description:
      "Tender spinach leaves grown under residue-free protocols and chilled immediately after harvest.",
    tags: ["Leafy", "Quick commerce", "Organic"],
    unit: "500 g",
    stock: 150,
    organic: true,
    price: 85,
    originalPrice: 110,
    deliveryTime: "Same day",
    rating: 4.6,
    reviewCount: 71,
    images: [
      "from-green-200 via-emerald-100 to-white",
      "from-lime-200 via-green-100 to-white",
      "from-emerald-200 via-lime-100 to-white",
    ],
    color: "from-green-100 to-lime-50",
    harvestDate: "2026-04-27",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-3",
    name: "Farmhouse A2 Cow Ghee",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "dairy",
    state: "Karnataka",
    description:
      "Bilona churned A2 ghee prepared in small batches from grass-fed desi cows with complete traceability.",
    tags: ["Premium", "Dairy", "Wholesaler"],
    unit: "1 litre",
    stock: 46,
    organic: false,
    price: 1299,
    originalPrice: 1450,
    deliveryTime: "2-4 days",
    rating: 4.9,
    reviewCount: 94,
    images: [
      "from-yellow-200 via-orange-50 to-white",
      "from-amber-200 via-yellow-50 to-white",
      "from-stone-200 via-yellow-50 to-white",
    ],
    color: "from-yellow-100 to-orange-50",
    harvestDate: "2026-04-15",
    featured: true,
    trending: false,
  }),
  buildProduct({
    id: "prod-4",
    name: "Stoneground Multigrain Atta",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "grains",
    state: "Karnataka",
    description:
      "A nourishing blend of wheat, ragi, jowar, and chana milled fresh for direct household and retail sale.",
    tags: ["Millets", "Retail", "Healthy"],
    unit: "5 kg",
    stock: 60,
    organic: true,
    price: 399,
    originalPrice: 470,
    deliveryTime: "2-3 days",
    rating: 4.5,
    reviewCount: 49,
    images: [
      "from-stone-200 via-amber-50 to-white",
      "from-yellow-100 via-stone-50 to-white",
      "from-orange-100 via-stone-50 to-white",
    ],
    color: "from-yellow-100 to-stone-50",
    harvestDate: "2026-04-18",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-5",
    name: "Hybrid Tomato Seed Pack",
    farmerId: "farmer-1",
    farmerName: "Rakesh Kumar",
    category: "seeds",
    state: "Punjab",
    description:
      "High-germination tomato seeds recommended for protected cultivation with strong fruit firmness.",
    tags: ["Seed", "Nursery", "B2B"],
    unit: "250 g",
    stock: 120,
    organic: false,
    price: 260,
    originalPrice: 325,
    deliveryTime: "2-5 days",
    rating: 4.3,
    reviewCount: 35,
    images: [
      "from-rose-200 via-orange-100 to-white",
      "from-red-200 via-yellow-50 to-white",
      "from-orange-200 via-rose-100 to-white",
    ],
    color: "from-rose-100 to-orange-50",
    harvestDate: "2026-04-12",
    featured: false,
    trending: false,
  }),
  buildProduct({
    id: "prod-6",
    name: "Naturally Grown Red Onions",
    farmerId: "farmer-2",
    farmerName: "Anita Patil",
    category: "vegetables",
    state: "Maharashtra",
    description:
      "Sorted red onions with consistent sizing, suitable for home kitchens, kirana stores, and wholesalers.",
    tags: ["Bulk", "Retail", "Wholesaler"],
    unit: "10 kg",
    stock: 190,
    organic: false,
    price: 320,
    originalPrice: 390,
    deliveryTime: "1-3 days",
    rating: 4.4,
    reviewCount: 82,
    images: [
      "from-rose-200 via-pink-100 to-white",
      "from-red-200 via-rose-100 to-white",
      "from-orange-200 via-red-50 to-white",
    ],
    color: "from-rose-100 to-pink-50",
    harvestDate: "2026-04-26",
    featured: true,
    trending: true,
  }),
  buildProduct({
    id: "prod-7",
    name: "Organic Turmeric Fingers",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "organic",
    state: "Karnataka",
    description:
      "Sun-cured turmeric with bold colour and aroma, grown using low-input regenerative practices.",
    tags: ["Organic", "Spice", "Wholesale"],
    unit: "2 kg",
    stock: 76,
    organic: true,
    price: 540,
    originalPrice: 620,
    deliveryTime: "2-4 days",
    rating: 4.8,
    reviewCount: 51,
    images: [
      "from-yellow-200 via-lime-50 to-white",
      "from-amber-200 via-yellow-50 to-white",
      "from-orange-100 via-yellow-50 to-white",
    ],
    color: "from-yellow-100 to-lime-50",
    harvestDate: "2026-04-17",
    featured: false,
    trending: true,
  }),
  buildProduct({
    id: "prod-8",
    name: "Fresh Paneer Block",
    farmerId: "farmer-3",
    farmerName: "Mahesh Gowda",
    category: "dairy",
    state: "Karnataka",
    description:
      "Soft, high-protein paneer prepared daily and suitable for home kitchens, cafes, and retailers.",
    tags: ["Dairy", "Fresh", "HoReCa"],
    unit: "1 kg",
    stock: 33,
    organic: false,
    price: 360,
    originalPrice: 425,
    deliveryTime: "Same day",
    rating: 4.7,
    reviewCount: 64,
    images: [
      "from-slate-100 via-white to-sky-50",
      "from-stone-100 via-white to-cyan-50",
      "from-slate-200 via-white to-blue-50",
    ],
    color: "from-slate-100 to-cyan-50",
    harvestDate: "2026-04-28",
    featured: true,
    trending: false,
  }),
];

export const reviewsByProduct: Record<string, Review[]> = {
  "prod-1": [
    {
      id: "review-1",
      userName: "Neha S.",
      rating: 5,
      comment: "Perfect ripeness and premium packing. Worth the seasonal premium.",
      createdAt: "2026-04-22",
    },
    {
      id: "review-2",
      userName: "FreshMart Retail",
      rating: 4,
      comment: "Uniform sizing and good shelf life for our weekend sale.",
      createdAt: "2026-04-21",
    },
  ],
  "prod-2": [
    {
      id: "review-3",
      userName: "Amit V.",
      rating: 5,
      comment: "Leaves were crisp and clean, delivered in a cool pouch.",
      createdAt: "2026-04-27",
    },
  ],
};

export const users: DemoUser[] = [
  {
    id: "user-1",
    name: "Priya Sharma",
    email: "buyer@greencart.in",
    mobile: "9876543210",
    role: "buyer",
    password: "password123",
    avatar: "PS",
    wishlist: ["prod-1", "prod-7"],
    addresses: [
      {
        id: "addr-1",
        label: "Home",
        recipient: "Priya Sharma",
        line1: "42, Green Residency, Sector 62",
        city: "Noida",
        state: "Uttar Pradesh",
        pincode: "201301",
        phone: "9876543210",
        primary: true,
      },
    ],
  },
  {
    id: "user-2",
    name: "Rakesh Kumar",
    email: "farmer@greencart.in",
    mobile: "9988776655",
    role: "farmer",
    password: "password123",
    avatar: "RK",
    farmerId: "farmer-1",
    wishlist: ["prod-3"],
    addresses: [
      {
        id: "addr-2",
        label: "Farm Office",
        recipient: "Rakesh Kumar",
        line1: "Village Jodhan, Ludhiana",
        city: "Ludhiana",
        state: "Punjab",
        pincode: "141001",
        phone: "9988776655",
        primary: true,
      },
    ],
  },
  {
    id: "user-3",
    name: "Admin GreenCart",
    email: "admin@greencart.in",
    mobile: "9000000000",
    role: "admin",
    password: "password123",
    avatar: "AG",
    wishlist: [],
    addresses: [],
  },
];

export const orders: Order[] = [
  {
    id: "ORD-240401",
    userId: "user-1",
    items: [
      { productId: "prod-1", quantity: 1, price: 899 },
      { productId: "prod-2", quantity: 2, price: 85 },
    ],
    subtotal: 1069,
    deliveryCharge: 40,
    discount: 100,
    total: 1009,
    paymentMode: "UPI",
    status: "In Transit",
    placedAt: "2026-04-25T10:30:00.000Z",
    estimatedDelivery: "2026-04-30T18:00:00.000Z",
    address: users[0].addresses[0],
  },
  {
    id: "ORD-240389",
    userId: "user-1",
    items: [{ productId: "prod-4", quantity: 1, price: 399 }],
    subtotal: 399,
    deliveryCharge: 0,
    discount: 0,
    total: 399,
    paymentMode: "COD",
    status: "Delivered",
    placedAt: "2026-04-14T13:20:00.000Z",
    estimatedDelivery: "2026-04-17T18:00:00.000Z",
    address: users[0].addresses[0],
  },
];

export const mandiRatesFallback: MandiRate[] = [
  {
    commodity: "Onion",
    market: "Lasalgaon",
    state: "Maharashtra",
    modalPrice: 1800,
    minPrice: 1650,
    maxPrice: 1960,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Tomato",
    market: "Kolar",
    state: "Karnataka",
    modalPrice: 1250,
    minPrice: 980,
    maxPrice: 1380,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Potato",
    market: "Agra",
    state: "Uttar Pradesh",
    modalPrice: 1420,
    minPrice: 1300,
    maxPrice: 1580,
    arrivalDate: "2026-04-28",
  },
  {
    commodity: "Mango",
    market: "Vashi",
    state: "Maharashtra",
    modalPrice: 5200,
    minPrice: 4700,
    maxPrice: 6100,
    arrivalDate: "2026-04-28",
  },
];

export const weatherInsightsFallback: WeatherInsight[] = [
  {
    title: "Rainfall watch",
    value: "18 mm",
    note: "Moderate showers expected across western Maharashtra over the next 48 hours.",
  },
  {
    title: "Soil moisture",
    value: "62%",
    note: "Good field moisture in Punjab vegetable belts; irrigation can be deferred for leafy crops.",
  },
  {
    title: "Crop alert",
    value: "Mango thrips",
    note: "Use sticky traps and field scouting in high humidity clusters.",
  },
];

export const farmerSalesMetrics: DashboardMetric[] = [
  {
    label: "This month sales",
    value: "₹1.84L",
    change: "+14.2%",
    tone: "positive",
  },
  {
    label: "Pending dispatches",
    value: "26",
    change: "6 due today",
    tone: "warning",
  },
  {
    label: "Average order value",
    value: "₹1,420",
    change: "+6.8%",
    tone: "positive",
  },
  {
    label: "Catalogue health",
    value: "92%",
    change: "3 items low stock",
    tone: "neutral",
  },
];

export const adminMetrics: DashboardMetric[] = [
  {
    label: "GMV this month",
    value: "₹18.6L",
    change: "+18%",
    tone: "positive",
  },
  {
    label: "Verified farmers",
    value: "128",
    change: "12 pending review",
    tone: "neutral",
  },
  {
    label: "Orders today",
    value: "482",
    change: "+9.1%",
    tone: "positive",
  },
  {
    label: "Support SLA",
    value: "97%",
    change: "Healthy",
    tone: "positive",
  },
];
